/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  QuickReaderPlugin: () => QuickReaderPlugin,
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/quick-modal.ts
var obsidian2 = __toESM(require("obsidian"));

// src/rsvp-engine.ts
var RSVPEngine = class {
  constructor(settings, onWordChange) {
    this.words = [];
    this.currentIndex = 0;
    this.isPlaying = false;
    this.timer = null;
    this.headings = [];
    this.paragraphs = [];
    // Acceleration & Timers
    this.startTime = 0;
    this.pauseTime = 0;
    this.totalPausedTime = 0;
    this.settings = settings;
    this.onWordChange = onWordChange;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Loads text into the engine and parses structure
   */
  loadText(words, headings = [], paragraphs = []) {
    this.words = words;
    this.headings = headings;
    this.paragraphs = paragraphs;
    this.currentIndex = 0;
    this.isPlaying = false;
    this.startTime = 0;
    this.totalPausedTime = 0;
  }
  getWords() {
    return this.words;
  }
  /**
   * Starts playback
   */
  play() {
    if (this.isPlaying)
      return;
    this.isPlaying = true;
    this.startTime = Date.now() - this.totalPausedTime;
    this.scheduleNextWord();
  }
  /**
   * Pauses playback
   */
  pause() {
    if (!this.isPlaying)
      return;
    this.isPlaying = false;
    this.pauseTime = Date.now();
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }
  /**
   * Toggle play/pause
   */
  toggle() {
    if (this.isPlaying)
      this.pause();
    else
      this.play();
  }
  /**
   * Jump to specific index or heading
   */
  jumpTo(index) {
    this.currentIndex = Math.max(0, Math.min(index, this.words.length - 1));
    this.notifyWord();
    if (this.isPlaying) {
      if (this.timer)
        clearTimeout(this.timer);
      this.scheduleNextWord();
    }
  }
  /**
   * Main scheduling loop
   */
  scheduleNextWord() {
    if (this.timer)
      clearTimeout(this.timer);
    if (!this.isPlaying || this.currentIndex >= this.words.length) {
      this.isPlaying = false;
      return;
    }
    const delay = this.calculateDelay();
    this.notifyWord();
    this.timer = window.setTimeout(() => {
      this.currentIndex++;
      this.scheduleNextWord();
    }, delay);
  }
  /**
   * calculates delay based on WPM, word length, and punctuation
   */
  calculateDelay() {
    const wpm = Math.max(10, this.settings.wpm);
    let currentWpm = wpm;
    if (this.settings.enableAcceleration && this.isPlaying) {
      const elapsed = this.getElapsedTime();
      if (elapsed < this.settings.accelerationDuration) {
        const progress = elapsed / this.settings.accelerationDuration;
        currentWpm = this.settings.wpm + (this.settings.accelerationTargetWpm - this.settings.wpm) * progress;
      } else {
        currentWpm = this.settings.accelerationTargetWpm;
      }
    }
    const baseDelay = 6e4 / currentWpm;
    const currentWord = this.words[this.currentIndex];
    if (!this.settings.enableMicropause)
      return baseDelay;
    let multiplier = 1;
    if (/[.!?]$/.test(currentWord)) {
      multiplier *= this.settings.micropausePunctuation;
    } else if (/[,;:]$/.test(currentWord)) {
      multiplier *= this.settings.micropauseOtherPunctuation;
    }
    if (currentWord.length > 8) {
      multiplier *= this.settings.micropauseLongWords;
    }
    const isHeadingWord = this.headings.some(
      (h) => this.currentIndex >= h.wordIndex && this.currentIndex < h.wordIndex + (h.wordLength || 0)
    );
    if (isHeadingWord) {
      multiplier *= this.settings.micropauseSectionMarkers;
    }
    return baseDelay * multiplier;
  }
  /**
   * Notifies the UI about a word change
   */
  notifyWord() {
    const text = this.words[this.currentIndex];
    const isEnd = this.currentIndex >= this.words.length - 1;
    const breadcrumb = this.getHeadingBreadcrumb(this.currentIndex);
    const paragraph = this.paragraphs.find(
      (p) => this.currentIndex >= p.wordStartIndex && this.currentIndex <= p.wordEndIndex
    );
    const activeHeading = this.headings.find(
      (h) => this.currentIndex >= h.wordIndex && this.currentIndex < h.wordIndex + (h.wordLength || 0)
    );
    this.onWordChange({
      text,
      index: this.currentIndex,
      delay: this.calculateDelay(),
      isEnd,
      headingContext: {
        breadcrumb,
        current: breadcrumb.length > 0 ? breadcrumb[breadcrumb.length - 1] : null
      },
      paragraph,
      metadata: {
        headingLevel: activeHeading == null ? void 0 : activeHeading.level,
        calloutType: activeHeading == null ? void 0 : activeHeading.calloutType
      }
    });
  }
  getHeadingBreadcrumb(wordIndex) {
    const path = [];
    const activeHeadings = this.headings.filter((h) => h.wordIndex <= wordIndex);
    for (const h of activeHeadings) {
      while (path.length > 0 && path[path.length - 1].level >= h.level && h.level !== 0) {
        path.pop();
      }
      path.push(h);
    }
    return path;
  }
  // Getters
  getCurrentIndex() {
    return this.currentIndex;
  }
  getTotalWords() {
    return this.words.length;
  }
  getIsPlaying() {
    return this.isPlaying;
  }
  getHeadings() {
    return this.headings;
  }
  getElapsedTime() {
    if (this.startTime === 0)
      return 0;
    const now = this.isPlaying ? Date.now() : this.pauseTime;
    return Math.floor((now - this.startTime - this.totalPausedTime) / 1e3);
  }
  getRemainingTime() {
    const total = this.words.length;
    if (total === 0)
      return 0;
    const remaining = total - this.currentIndex;
    const baseWpm = Math.max(10, this.settings.wpm);
    return Math.ceil(remaining / (baseWpm / 60));
  }
};

// src/dom-registry.ts
var DOMRegistry = class {
  constructor() {
    this.elements = /* @__PURE__ */ new Map();
  }
  /**
   * Register a DOM element
   */
  register(key, el) {
    this.elements.set(key, el);
  }
  /**
   * Retrieve a registered element
   */
  get(key) {
    return this.elements.get(key);
  }
  /**
   * Safe getter that throws if element is missing
   */
  getRequired(key) {
    const el = this.get(key);
    if (!el)
      throw new Error(`Required DOM element '${key}' not found in registry`);
    return el;
  }
  /**
   * Update the text content of a registered element
   */
  updateText(key, text) {
    const el = this.get(key);
    if (el)
      el.setText(text);
  }
  /**
   * Toggle a CSS class on a registered element
   */
  toggleClass(key, cls, state) {
    const el = this.get(key);
    if (el)
      el.toggleClass(cls, state != null ? state : !el.classList.contains(cls));
  }
  /**
   * Update multiple element texts in one call
   */
  batchUpdateText(updates) {
    Object.entries(updates).forEach(([key, text]) => {
      this.updateText(key, text);
    });
  }
  /**
   * Clear the registry
   */
  clear() {
    this.elements.clear();
  }
};

// src/word-display.ts
var WordDisplay = class {
  constructor(container, settings) {
    this.container = container;
    this.settings = settings;
    this.applyBaseStyles();
  }
  applyBaseStyles() {
    this.container.style.fontSize = `${this.settings.fontSize}px`;
    this.container.style.fontFamily = this.settings.fontFamily;
    this.container.style.color = this.settings.fontColor;
  }
  /**
   * Main rendering method for the current word chunk
   */
  render(chunk) {
    var _a, _b;
    this.container.empty();
    const isHeading = ((_a = chunk.metadata) == null ? void 0 : _a.headingLevel) !== void 0 && chunk.metadata.headingLevel > 0;
    this.container.toggleClass("is-heading", isHeading);
    if (isHeading) {
      this.container.setAttribute("data-level", String((_b = chunk.metadata) == null ? void 0 : _b.headingLevel));
    } else {
      this.container.removeAttribute("data-level");
    }
    const words = chunk.text.split(" ");
    if (words.length === 1) {
      this.renderSingleWord(words[0]);
    } else {
      this.renderMultiWord(words);
    }
  }
  /**
   * Renders a single word with ORP highlighting
   */
  renderSingleWord(word) {
    if (!word)
      return;
    const baseSize = this.settings.fontSize;
    if (word.length > 13) {
      const scaleFactor = Math.max(0.6, 1 - (word.length - 13) * 0.05);
      this.container.style.fontSize = `${baseSize * scaleFactor}px`;
    } else {
      this.container.style.fontSize = `${baseSize}px`;
    }
    const orpIndex = this.calculateORP(word);
    const leftText = word.substring(0, orpIndex);
    const leftWing = this.container.createDiv({ cls: "qr-word-left-wing" });
    leftWing.setText(leftText || "");
    const orpChar = word.charAt(orpIndex);
    this.container.createDiv({ text: orpChar, cls: "qr-word-orp" });
    const rightText = word.substring(orpIndex + 1);
    const rightWing = this.container.createDiv({ cls: "qr-word-right-wing" });
    rightWing.setText(rightText || "");
  }
  renderMultiWord(words) {
    this.container.setText(words.join(" "));
  }
  /**
   * Optimal Recognition Point calculation
   * Usually 25% to 35% into the word
   */
  calculateORP(word) {
    const len = word.length;
    if (len <= 1)
      return 0;
    if (len <= 5)
      return 1;
    if (len <= 9)
      return 2;
    if (len <= 13)
      return 3;
    return 4;
  }
  /**
   * Update display settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.applyBaseStyles();
  }
  showReady(fileName, totalWords, wpm, contentSnippet) {
    this.container.empty();
    const readyContainer = this.container.createDiv({ cls: "qr-dashboard" });
    const header = readyContainer.createDiv({ cls: "qr-db-header" });
    header.createEl("h1", { text: fileName, cls: "qr-db-title" });
    const meta = header.createDiv({ cls: "qr-db-meta" });
    const minutes = Math.ceil(totalWords / wpm);
    this.createPill(meta, "book-open", `${totalWords} words`);
    this.createPill(meta, "clock", `${minutes} min read`);
    this.createPill(meta, "zap", `${wpm} WPM`);
    const preview = readyContainer.createDiv({ cls: "qr-db-preview" });
    preview.createDiv({ cls: "qr-db-preview-label", text: "DOCUMENT PREVIEW" });
    preview.createDiv({ cls: "qr-db-preview-text", text: contentSnippet + "..." });
    const shortcuts = readyContainer.createDiv({ cls: "qr-db-shortcuts" });
    this.createShortcut(shortcuts, "Space", "Play / Pause");
    this.createShortcut(shortcuts, "\u2191 / \u2193", "Speed +/- 25");
    this.createShortcut(shortcuts, "\u2190 / \u2192", "Seek 10 Words");
    this.createShortcut(shortcuts, "C", "Toggle Context");
    this.createShortcut(shortcuts, "Esc", "Close Reader");
    const cta = readyContainer.createDiv({ cls: "qr-db-cta" });
    cta.createDiv({ text: "PRESS SPACE TO START", cls: "qr-db-pulse-text" });
  }
  createPill(parent, icon, text) {
    const pill = parent.createDiv({ cls: "qr-db-pill" });
    pill.createSpan({ text: icon === "book-open" ? "\u{1F4D6}" : icon === "clock" ? "\u23F1\uFE0F" : "\u26A1", cls: "qr-db-pill-icon" });
    pill.createSpan({ text });
  }
  createShortcut(parent, key, label) {
    const item = parent.createDiv({ cls: "qr-db-shortcut-item" });
    item.createSpan({ text: key, cls: "qr-db-key" });
    item.createSpan({ text: label, cls: "qr-db-label" });
  }
  clear() {
    this.container.empty();
  }
};

// src/breadcrumb-manager.ts
var import_obsidian = require("obsidian");
var BreadcrumbManager = class {
  constructor(container, engine) {
    this.CALLOUT_ICONS = {
      note: "\u{1F4DD}",
      abstract: "\u{1F4C4}",
      info: "\u2139\uFE0F",
      tip: "\u{1F4A1}",
      success: "\u2705",
      question: "\u2753",
      warning: "\u26A0\uFE0F",
      failure: "\u274C",
      danger: "\u26A1",
      bug: "\u{1F41B}",
      example: "\u{1F4CB}",
      quote: "\u{1F4AC}"
    };
    this.container = container;
    this.engine = engine;
  }
  /**
   * Updates the interactive breadcrumb trail, always starting with the Note Title
   */
  update(breadcrumb, noteTitle) {
    this.container.empty();
    const rootPill = this.container.createSpan({
      cls: `qr-breadcrumb-pill qr-breadcrumb-root ${breadcrumb.length === 0 ? "is-active" : ""}`
    });
    rootPill.createSpan({ text: "\u{1F4C4} ", cls: "qr-breadcrumb-icon" });
    rootPill.createSpan({ text: noteTitle, cls: "qr-breadcrumb-text" });
    rootPill.addEventListener("click", (e) => {
      e.stopPropagation();
      this.engine.jumpTo(0);
    });
    breadcrumb.forEach((heading, index) => {
      this.container.createSpan({ text: " \u203A ", cls: "qr-breadcrumb-separator" });
      const pill = this.container.createSpan({
        cls: `qr-breadcrumb-pill ${index === breadcrumb.length - 1 ? "is-active" : ""}`
      });
      const icon = heading.calloutType ? this.CALLOUT_ICONS[heading.calloutType.toLowerCase()] || "\u{1F4CC}" : "";
      if (icon) {
        pill.createSpan({ text: icon, cls: "qr-breadcrumb-icon" });
      }
      pill.createSpan({ text: heading.text, cls: "qr-breadcrumb-text" });
      pill.addEventListener("click", (e) => {
        e.stopPropagation();
        this.engine.jumpTo(heading.wordIndex);
      });
    });
    const dropdown = this.container.createSpan({
      cls: "qr-breadcrumb-dropdown",
      text: " \u25BC"
    });
    dropdown.addEventListener("click", (e) => {
      e.stopPropagation();
      this.showOutline(dropdown);
    });
  }
  /**
   * Shows a hierarchical document outline
   */
  showOutline(anchor) {
    const allHeadings = this.engine.getHeadings();
    if (allHeadings.length === 0)
      return;
    const menu = new import_obsidian.Menu();
    allHeadings.forEach((h) => {
      const indentation = "  ".repeat(Math.max(0, h.level - 1));
      const icon = h.calloutType ? this.CALLOUT_ICONS[h.calloutType.toLowerCase()] || "\u{1F4CC}" : "";
      menu.addItem((item) => {
        item.setTitle(`${indentation}${icon} ${h.text}`).onClick(() => this.engine.jumpTo(h.wordIndex));
      });
    });
    const rect = anchor.getBoundingClientRect();
    menu.showAtPosition({ x: rect.left, y: rect.bottom + 5 });
  }
  clear() {
    this.container.empty();
  }
};

// src/minimap-manager.ts
var MinimapManager = class {
  constructor(container, engine) {
    this.progressBar = null;
    this.tooltip = null;
    this.points = [];
    this.headings = [];
    this.activeHeadingIndex = -1;
    this.container = container;
    this.engine = engine;
    this.init();
  }
  init() {
    this.progressBar = this.container.createDiv({ cls: "qr-minimap-progress" });
    this.tooltip = document.body.createDiv({ cls: "qr-minimap-tooltip" });
  }
  /**
   * Renders the note hierarchy on the minimap SPINE
   */
  render(headings, totalWords) {
    this.points.forEach((p) => p.remove());
    this.points = [];
    this.headings = headings;
    if (totalWords === 0)
      return;
    headings.forEach((h, index) => {
      const point = this.container.createDiv({ cls: "qr-minimap-point" });
      const percentage = h.wordIndex / totalWords * 100;
      point.style.top = `${percentage}%`;
      point.setAttr("data-level", h.level);
      point.addEventListener("click", (e) => {
        e.stopPropagation();
        this.smartJump(h.wordIndex);
      });
      point.addEventListener("mouseenter", () => this.showTooltip(h.text, point));
      point.addEventListener("mouseleave", () => this.hideTooltip());
      this.points.push(point);
    });
  }
  /**
   * Jumps to word and provides a brief orientation pause
   */
  smartJump(wordIndex) {
    const wasPlaying = this.engine.getIsPlaying();
    if (wasPlaying)
      this.engine.pause();
    this.engine.jumpTo(wordIndex);
    if (wasPlaying) {
      setTimeout(() => {
        this.engine.play();
      }, 400);
    }
  }
  showTooltip(text, pointEl) {
    if (!this.tooltip)
      return;
    this.tooltip.setText(text);
    const rect = pointEl.getBoundingClientRect();
    const tooltipHeight = this.tooltip.offsetHeight || 30;
    this.tooltip.style.top = `${rect.top + rect.height / 2 - tooltipHeight / 2}px`;
    this.tooltip.classList.add("is-visible");
  }
  hideTooltip() {
    if (this.tooltip)
      this.tooltip.classList.remove("is-visible");
  }
  /**
   * Frame-perfect progress update
   */
  update(currentIndex, totalWords) {
    if (!this.progressBar || totalWords <= 0) {
      if (this.progressBar)
        this.progressBar.style.height = "0%";
      return;
    }
    const percentage = currentIndex / totalWords * 100;
    this.progressBar.style.height = `${percentage}%`;
    let newIndex = -1;
    for (let i = this.headings.length - 1; i >= 0; i--) {
      if (currentIndex >= this.headings[i].wordIndex) {
        newIndex = i;
        break;
      }
    }
    if (newIndex !== this.activeHeadingIndex) {
      if (this.activeHeadingIndex !== -1 && this.points[this.activeHeadingIndex]) {
        this.points[this.activeHeadingIndex].classList.remove("is-active");
      }
      if (newIndex !== -1 && this.points[newIndex]) {
        this.points[newIndex].classList.add("is-active");
      }
      this.activeHeadingIndex = newIndex;
    }
  }
  destroy() {
    if (this.tooltip)
      this.tooltip.remove();
  }
};

// src/markdown-parser.ts
var MarkdownParser = class {
  static parse(markdown) {
    const headings = [];
    const paragraphs = [];
    const cleanWords = [];
    let cleanMarkdown = markdown.replace(/^---[\s\S]*?---\n?/m, "");
    cleanMarkdown = cleanMarkdown.replace(/%%[\s\S]*?%%/g, "");
    const lines = cleanMarkdown.split("\n");
    let currentWordIndex = 0;
    let currentParaStartIndex = null;
    let paraBuffer = [];
    for (let line of lines) {
      const trimmed = line.trim();
      const headingMatch = trimmed.match(/^(#{1,6})\s+(.+)$/);
      if (headingMatch) {
        this.saveParagraph(paragraphs, currentParaStartIndex, currentWordIndex, paraBuffer);
        currentParaStartIndex = null;
        paraBuffer = [];
        const level = headingMatch[1].length;
        const text = this.cleanLine(headingMatch[2]);
        const headingWords = text.split(/\s+/).filter((w) => w.length > 0);
        headings.push({
          level,
          text: headingWords.join(" "),
          wordIndex: currentWordIndex,
          wordLength: headingWords.length
        });
        headingWords.forEach((w) => {
          cleanWords.push(w);
          currentWordIndex++;
        });
        continue;
      }
      const calloutMatch = trimmed.match(/^>\s*\[!([\w-]+)\]\s*(.*)$/);
      if (calloutMatch) {
        this.saveParagraph(paragraphs, currentParaStartIndex, currentWordIndex, paraBuffer);
        currentParaStartIndex = null;
        paraBuffer = [];
        const type = calloutMatch[1];
        const title = calloutMatch[2].trim() || type;
        const text = this.cleanLine(title);
        const callWords = text.split(/\s+/).filter((w) => w.length > 0);
        headings.push({
          level: 0,
          text: callWords.join(" "),
          wordIndex: currentWordIndex,
          wordLength: callWords.length,
          calloutType: type
        });
        callWords.forEach((w) => {
          cleanWords.push(w);
          currentWordIndex++;
        });
        continue;
      }
      if (trimmed === "") {
        this.saveParagraph(paragraphs, currentParaStartIndex, currentWordIndex, paraBuffer);
        currentParaStartIndex = null;
        paraBuffer = [];
        continue;
      }
      const cleanLineText = this.cleanLine(line);
      const wordsOnLine = cleanLineText.split(/\s+/).filter((w) => w.length > 0);
      if (wordsOnLine.length > 0) {
        if (currentParaStartIndex === null)
          currentParaStartIndex = currentWordIndex;
        wordsOnLine.forEach((w) => {
          cleanWords.push(w);
          paraBuffer.push(w);
          currentWordIndex++;
        });
      }
    }
    this.saveParagraph(paragraphs, currentParaStartIndex, currentWordIndex, paraBuffer);
    return {
      words: cleanWords,
      headings,
      paragraphs
    };
  }
  static saveParagraph(paras, start, current, buffer) {
    if (start !== null && buffer.length > 0) {
      paras.push({
        wordStartIndex: start,
        wordEndIndex: current - 1,
        text: buffer.join(" ")
      });
    }
  }
  /**
   * Cleans a single line of text from Markdown syntax
   */
  static cleanLine(line) {
    let t = line;
    t = t.replace(/%%[\s\S]*?%%/g, "");
    t = t.replace(/!\[\[([^\]|]+)(\|([^\]]+))?\]\]/g, "$3");
    t = t.replace(/\[\[([^\]|]+)(\|([^\]]+))?\]\]/g, (_m, link, _p, alias) => alias || link);
    t = t.replace(/!\[[^\]]*\]\([^)]+\)/g, "");
    t = t.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
    t = t.replace(/\*\*\*([^*]+)\*\*\*/g, "$1");
    t = t.replace(/\*\*([^*]+)\*\*/g, "$1");
    t = t.replace(/__([^_]+)__/g, "$1");
    t = t.replace(/\*([^*\n]+)\*/g, "$1");
    t = t.replace(/_([^_\n]+)_/g, "$1");
    t = t.replace(/~~([^~]+)~~/g, "$1");
    t = t.replace(/==([^=]+)==/g, "$1");
    t = t.replace(/`([^`]+)`/g, "$1");
    t = t.replace(/<[^>]+>/g, "");
    t = t.replace(/\[\^[^\]]+\]/g, "");
    t = t.replace(/\$[^$]+\$/g, "[MATH]");
    t = t.replace(/^>\s*/gm, "");
    t = t.replace(/^[\s]*[-*+]\s+\[.\]\s*/gm, "");
    t = t.replace(/^[\s]*[-*+]\s+/gm, "");
    t = t.replace(/^[\s]*\d+\.\s+/gm, "");
    t = t.replace(/(?:^|\s)(#[a-zA-Z0-9_/-]+)/g, "");
    t = t.replace(/\s+\^[a-zA-Z0-9-]+$/gm, "");
    return t.trim();
  }
};

// src/constants.ts
var CSS_CLASSES = {
  // Main Container
  container: "quick-reader-container",
  modal: "quick-reader-zen-modal",
  modalContent: "quick-reader-modal-content",
  // Layout Zones
  header: "qr-header",
  stage: "qr-stage",
  deck: "qr-deck",
  // Header Elements
  breadcrumb: "qr-breadcrumb",
  breadcrumbItem: "qr-breadcrumb-item",
  headerActions: "qr-header-actions",
  // Stage Elements
  display: "qr-display",
  word: "qr-word",
  wordFocus: "qr-word-focus",
  contextBefore: "qr-context-before",
  contextAfter: "qr-context-after",
  flowContainer: "qr-flow-container",
  flowWord: "qr-flow-word",
  // Deck Elements
  controls: "qr-controls",
  playbackStrip: "qr-playback-strip",
  liveStats: "qr-live-stats",
  progressBar: "qr-progress-bar",
  // Components
  btn: "qr-btn",
  iconBtn: "qr-icon-btn",
  controlGroup: "qr-control-group",
  valueDisplay: "qr-value-display",
  // States
  hidden: "qr-hidden",
  active: "qr-active",
  loading: "qr-loading",
  playing: "qr-playing",
  paused: "qr-paused"
};

// src/ui-builders.ts
var obsidian = __toESM(require("obsidian"));
function createIconButton(parent, config) {
  const btn = parent.createEl("button", {
    cls: `${CSS_CLASSES.iconBtn} ${config.cls || ""}`
  });
  if (typeof obsidian.setIcon === "function") {
    obsidian.setIcon(btn, config.icon);
  } else {
    btn.setText(config.icon);
  }
  btn.setAttr("title", config.title);
  btn.addEventListener("click", (e) => {
    e.stopPropagation();
    config.onClick(e);
  });
  return btn;
}
function createPlaybackToggle(parent, onToggle, registry) {
  const btn = parent.createEl("button", {
    cls: `qr-main-toggle ${CSS_CLASSES.btn}`
  });
  registry.register("playbackToggle", btn);
  if (typeof obsidian.setIcon === "function") {
    obsidian.setIcon(btn, "play");
  } else {
    btn.setText("PLAY");
  }
  btn.addEventListener("click", () => onToggle());
  return btn;
}
function updatePlaybackUI(registry, isPlaying) {
  const btn = registry.get("playbackToggle");
  if (!btn)
    return;
  const icon = isPlaying ? "pause" : "play";
  if (typeof obsidian.setIcon === "function") {
    obsidian.setIcon(btn, icon);
  } else {
    btn.setText(icon.toUpperCase());
  }
}

// src/quick-modal.ts
var ModalBase = obsidian2.Modal;
var QuickReaderModal = class extends ModalBase {
  constructor(app, plugin) {
    super(app);
    this.dom = new DOMRegistry();
    this.lastBreadcrumbId = "__INIT__";
    this.noteTitle = "";
    this.plugin = plugin;
    this.settings = plugin.settings;
    this.modalEl.classList.add(CSS_CLASSES.modal);
    this.contentEl.classList.add(CSS_CLASSES.modalContent);
    this.containerEl.addClass("qr-backdrop-blur");
    this.engine = new RSVPEngine(this.settings, (chunk) => this.onWordChange(chunk));
  }
  onOpen() {
    this.buildUI();
    this.setupHotkeys();
    if (this.engine.getTotalWords() > 0) {
      this.renderInitialState();
    }
  }
  onClose() {
    this.engine.pause();
    this.dom.clear();
    this.contentEl.empty();
  }
  buildUI() {
    const container = this.contentEl.createDiv({ cls: CSS_CLASSES.container });
    this.dom.register("modal", container);
    const header = container.createDiv({ cls: CSS_CLASSES.header });
    this.dom.register("header", header);
    const breadcrumbEl = header.createDiv({ cls: CSS_CLASSES.breadcrumb });
    if (!this.settings.showBreadcrumb) {
      breadcrumbEl.classList.add("qr-hidden");
    }
    this.breadcrumbManager = new BreadcrumbManager(breadcrumbEl, this.engine);
    this.dom.register("breadcrumb", breadcrumbEl);
    const actions = header.createDiv({ cls: CSS_CLASSES.headerActions });
    this.buildHeaderActions(actions);
    const stage = container.createDiv({ cls: CSS_CLASSES.stage });
    this.dom.register("stage", stage);
    const display = stage.createDiv({ cls: CSS_CLASSES.display });
    this.wordDisplay = new WordDisplay(display, this.settings);
    this.dom.register("display", display);
    const expansion = stage.createDiv({ cls: "qr-expansion qr-hidden" });
    this.dom.register("flowContainer", expansion);
    const minimapContainer = stage.createDiv({ cls: "qr-minimap-container" });
    if (!this.settings.showMinimap) {
      minimapContainer.classList.add("qr-hidden");
    }
    this.minimapManager = new MinimapManager(minimapContainer, this.engine);
    const deck = container.createDiv({ cls: CSS_CLASSES.deck });
    this.dom.register("deck", deck);
    const playback = deck.createDiv({ cls: CSS_CLASSES.playbackStrip });
    createPlaybackToggle(playback, () => this.engine.toggle(), this.dom);
    const stats = deck.createDiv({ cls: CSS_CLASSES.liveStats });
    this.dom.register("stats", stats);
  }
  buildHeaderActions(container) {
    createIconButton(container, {
      icon: "settings",
      title: "Settings",
      onClick: () => {
        this.close();
        const setting = this.app.setting;
        if (setting) {
          setting.open();
          setting.openTabById("quick-reader");
        }
      }
    });
    createIconButton(container, {
      icon: "x",
      title: "Close",
      onClick: () => this.close()
    });
  }
  setupHotkeys() {
    this.scope.register([], " ", (evt) => {
      evt.preventDefault();
      this.engine.toggle();
      return false;
    });
    this.scope.register([], "Escape", () => this.close());
    this.scope.register([], "ArrowLeft", (evt) => {
      evt.preventDefault();
      this.engine.jumpTo(this.engine.getCurrentIndex() - 10);
    });
    this.scope.register([], "ArrowRight", (evt) => {
      evt.preventDefault();
      this.engine.jumpTo(this.engine.getCurrentIndex() + 10);
    });
    this.scope.register([], "ArrowUp", (evt) => {
      evt.preventDefault();
      this.adjustWPM(25);
    });
    this.scope.register([], "ArrowDown", (evt) => {
      evt.preventDefault();
      this.adjustWPM(-25);
    });
    this.scope.register([], "KeyC", () => this.toggleExpansion());
  }
  adjustWPM(delta) {
    this.settings.wpm = Math.max(50, Math.min(2e3, this.settings.wpm + delta));
    this.engine.updateSettings(this.settings);
    this.plugin.saveSettings();
    this.updateStats();
    if (this.engine.getCurrentIndex() === 0 && !this.engine.getIsPlaying()) {
      this.renderInitialState();
    }
  }
  toggleExpansion() {
    if (this.engine.getIsPlaying())
      return;
    this.dom.toggleClass("flowContainer", CSS_CLASSES.hidden);
    this.dom.toggleClass("display", CSS_CLASSES.hidden);
  }
  onWordChange(chunk) {
    if (chunk.index === 0 && !this.engine.getIsPlaying()) {
      this.updateStats();
      return;
    }
    if (this.engine.getIsPlaying()) {
      this.dom.toggleClass("flowContainer", CSS_CLASSES.hidden, true);
      this.dom.toggleClass("display", CSS_CLASSES.hidden, false);
      this.wordDisplay.render(chunk);
    } else if (this.settings.enableContextExpansion) {
      this.renderExpandedContext(chunk);
    }
    if (chunk.headingContext) {
      const breadcrumbId = chunk.headingContext.breadcrumb.map((h) => h.text).join("|");
      if (breadcrumbId !== this.lastBreadcrumbId) {
        this.breadcrumbManager.update(chunk.headingContext.breadcrumb, this.noteTitle);
        this.lastBreadcrumbId = breadcrumbId;
      }
    }
    this.minimapManager.update(chunk.index, this.engine.getTotalWords());
    updatePlaybackUI(this.dom, this.engine.getIsPlaying());
    this.updateStats();
  }
  updateStats() {
    const stats = `Word ${this.engine.getCurrentIndex() + 1}/${this.engine.getTotalWords()} \u2022 ${this.settings.wpm} WPM`;
    this.dom.updateText("stats", stats);
  }
  renderExpandedContext(chunk) {
    const expansion = this.dom.getRequired("flowContainer");
    const display = this.dom.getRequired("display");
    if (!chunk.paragraph) {
      this.wordDisplay.render(chunk);
      return;
    }
    display.classList.add(CSS_CLASSES.hidden);
    expansion.classList.remove(CSS_CLASSES.hidden);
    expansion.empty();
    const words = chunk.paragraph.text.split(" ");
    const relativeIndex = chunk.index - chunk.paragraph.wordStartIndex;
    words.forEach((word, i) => {
      const span = expansion.createSpan({ text: word + " ", cls: "qr-expansion-word" });
      if (i === relativeIndex) {
        span.classList.add("qr-active-word");
      }
    });
  }
  openWithText(text, fileName = "Note") {
    this.noteTitle = fileName;
    const { words, headings, paragraphs } = MarkdownParser.parse(text);
    this.engine.loadText(words, headings, paragraphs);
    this.open();
    this.renderInitialState();
  }
  renderInitialState() {
    if (!this.wordDisplay)
      return;
    const display = this.dom.getRequired("display");
    const flow = this.dom.getRequired("flowContainer");
    display.classList.remove(CSS_CLASSES.hidden);
    flow.classList.add(CSS_CLASSES.hidden);
    this.breadcrumbManager.update([], this.noteTitle);
    this.minimapManager.render(this.engine.getHeadings(), this.engine.getTotalWords());
    const words = this.engine.getWords();
    const previewText = words.slice(0, 25).join(" ");
    this.wordDisplay.showReady(this.noteTitle, this.engine.getTotalWords(), this.settings.wpm, previewText);
    this.updateStats();
    setTimeout(() => {
      display.classList.remove(CSS_CLASSES.hidden);
      display.style.display = "flex";
      flow.classList.add(CSS_CLASSES.hidden);
    }, 50);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  wpm: 400,
  chunkSize: 1,
  fontSize: 52,
  // Slightly larger base for Quick Reader
  highlightColor: "#4a9eff",
  backgroundColor: "#0f141e",
  // Deeper, more premium charcoal
  fontColor: "#f5f5f5",
  fontFamily: "Outfit, Inter, sans-serif",
  accentColor: "#007aff",
  showContext: false,
  contextWords: 3,
  showMinimap: true,
  showBreadcrumb: true,
  showProgress: true,
  showStats: true,
  showFlowText: false,
  flowTextOpacity: 0.1,
  enableMicropause: true,
  micropausePunctuation: 2.2,
  micropauseOtherPunctuation: 1.4,
  micropauseLongWords: 1.3,
  micropauseParagraph: 2.2,
  micropauseNumbers: 1.6,
  micropauseSectionMarkers: 1.8,
  micropauseListBullets: 1.6,
  micropauseCallouts: 2,
  autoStart: false,
  autoStartDelay: 3,
  enableSlowStart: true,
  enableAcceleration: false,
  accelerationDuration: 30,
  accelerationTargetWpm: 600,
  hotkeyPlay: "Space",
  hotkeyRewind: "ArrowLeft",
  hotkeyForward: "ArrowRight",
  hotkeyIncrementWpm: "ArrowUp",
  hotkeyDecrementWpm: "ArrowDown",
  hotkeyQuit: "Escape",
  enableContextExpansion: true,
  expansionHotkey: "KeyC"
};

// src/settings.ts
var QuickReaderSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Quick Reader Settings" });
    new import_obsidian2.Setting(containerEl).setName("Reading Speed (WPM)").setDesc("Words per minute for the RSVP engine.").addSlider((slider) => slider.setLimits(100, 1500, 50).setValue(this.plugin.settings.wpm).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.wpm = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Font Size").setDesc("Size of the word display in the modal.").addSlider((slider) => slider.setLimits(24, 120, 4).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fontSize = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Visual Features" });
    new import_obsidian2.Setting(containerEl).setName("Context Reveal (Expansion)").setDesc("Automatically expand the paragraph context when paused.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableContextExpansion).onChange(async (value) => {
      this.plugin.settings.enableContextExpansion = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show Minimap").setDesc("Displays a vertical progress bar with heading points.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showMinimap).onChange(async (value) => {
      this.plugin.settings.showMinimap = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show Breadcrumbs").setDesc("Displays the heading hierarchy at the top.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showBreadcrumb).onChange(async (value) => {
      this.plugin.settings.showBreadcrumb = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show Stats").setDesc("Displays real-time reading statistics.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStats).onChange(async (value) => {
      this.plugin.settings.showStats = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Reset" });
    new import_obsidian2.Setting(containerEl).setName("Reset to Defaults").setDesc("Restore all settings to factory defaults.").addButton((btn) => btn.setButtonText("Reset").setWarning().onClick(async () => {
      this.plugin.settings = Object.assign({}, DEFAULT_SETTINGS);
      await this.plugin.saveSettings();
      this.display();
    }));
  }
};

// src/main.ts
var QuickReaderPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("zap", "Open Quick Reader", () => {
      this.openReader();
    });
    this.addCommand({
      id: "open-reader-note",
      name: "Read entire note",
      callback: () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view) {
          this.openReader(view.editor.getValue());
        } else {
          new import_obsidian3.Notice("Please open a note first");
        }
      }
    });
    this.addCommand({
      id: "open-reader-selection",
      name: "Read selection",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (selection) {
          this.openReader(selection);
        } else {
          new import_obsidian3.Notice("Please select some text first");
        }
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selection = editor.getSelection();
        if (selection) {
          menu.addItem((item) => {
            item.setTitle("Read with Quick Reader").setIcon("zap").onClick(() => this.openReader(selection));
          });
        }
      })
    );
    this.addSettingTab(new QuickReaderSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Helper to open the modal with specific text
   */
  openReader(text) {
    const modal = new QuickReaderModal(this.app, this);
    const activeFile = this.app.workspace.getActiveFile();
    const fileName = activeFile ? activeFile.basename : "Selection";
    if (text) {
      modal.openWithText(text, fileName);
    } else {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (view) {
        modal.openWithText(view.editor.getValue(), fileName);
      } else {
        new import_obsidian3.Notice("No text to read. Please open a note.");
      }
    }
  }
};
var main_default = QuickReaderPlugin;
